export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_NEW_ATTR_FOR_CATE = "CREATE_NEW_ATTR_FOR_CATE";
export const INSERT_NEW_CATEGORY = "INSERT_NEW_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
